rename_columns = {
    "Respondent name": "name",
    "Respondent unique ID": "id",
    "Answer created": "time_started",
    "Answer complete": "time_completed",
    "Personal Questions : Q1.1 – Current primary role (single-choice)": "role",
    "Personal Questions : Other": "text_role_other",
    "Personal Questions : Q1.2 – Years of professional software experience (approximate)": "years_experience",
    "Personal Questions : Q1.3 – Main software domain you work in (multi-choice) : Web/Cloud services": "domain_web",
    "Personal Questions : Q1.3 – Main software domain you work in (multi-choice) : Mobile Applications": "domain_mobile",
    "Personal Questions : Q1.3 – Main software domain you work in (multi-choice) : Embedded / IoT": "domain_embedded",
    "Personal Questions : Q1.3 – Main software domain you work in (multi-choice) : Enterprise / Backend": "domain_enterprise",
    "Personal Questions : Q1.3 – Main software domain you work in (multi-choice) : AI / Machine Learning": "domain_ai",
    "Personal Questions : Q1.3 – Main software domain you work in (multi-choice) : Games": "domain_games",
    "Personal Questions : Q1.3 – Main software domain you work in (multi-choice) : Other": "domain_other",
    "Personal Questions : Other.1": "text_domain_other",
    "Personal Questions : Q4 – Anything else you want to share about your testing background that would help us interpret your answers? (such as change in role, domain etc.)": "domain_additional",
    "Personal Questions : Q1.5 – Familiarity with Boundary Value Analysis.": "bva_familiarity",
    "Personal Questions : Q1.6 In your own words, what should a boundary behaviour explanation that is presented to a tester contain?": "text_explanation_contain",
    "Email : Email Q2.1 — Rate the explanation of boundary pair \"EMAIL 1\" : Clear": "email_1_clarity",
    "Email : Email Q2.1 — Rate the explanation of boundary pair \"EMAIL 1\" : Correct": "email_1_correctness",
    "Email : Email Q2.1 — Rate the explanation of boundary pair \"EMAIL 1\" : Complete": "email_1_completeness",
    "Email : Email Q2.1 — Rate the explanation of boundary pair \"EMAIL 1\" : Useful": "email_1_usefulness",
    "Email : BMI Q2.2 — Rate the explanation of boundary pair \"EMAIL 2\" : Clear": "email_2_clarity",
    "Email : BMI Q2.2 — Rate the explanation of boundary pair \"EMAIL 2\" : Correct": "email_2_correctness",
    "Email : BMI Q2.2 — Rate the explanation of boundary pair \"EMAIL 2\" : Complete": "email_2_completeness",
    "Email : BMI Q2.2 — Rate the explanation of boundary pair \"EMAIL 2\" : Useful": "email_2_usefulness",
    "Email : EMAIL Q2.3 — Rate the explanation of boundary pair \"EMAIL 3\" : Clear": "email_3_clarity",
    "Email : EMAIL Q2.3 — Rate the explanation of boundary pair \"EMAIL 3\" : Correct": "email_3_correctness",
    "Email : EMAIL Q2.3 — Rate the explanation of boundary pair \"EMAIL 3\" : Complete": "email_3_completeness",
    "Email : EMAIL Q2.3 — Rate the explanation of boundary pair \"EMAIL 3\" : Useful": "email_3_usefulness",
    "Email : EMAIL Q2.4 — Rate the explanation of boundary pair \"EMAIL 4\" : Clear": "email_4_clarity",
    "Email : EMAIL Q2.4 — Rate the explanation of boundary pair \"EMAIL 4\" : Correct": "email_4_correctness",
    "Email : EMAIL Q2.4 — Rate the explanation of boundary pair \"EMAIL 4\" : Complete": "email_4_completeness",
    "Email : EMAIL Q2.4 — Rate the explanation of boundary pair \"EMAIL 4\" : Useful": "email_4_usefulness",
    "Email : EMAIL Q2.5 — Rate the explanation of boundary pair \"EMAIL 5\" : Clear": "email_5_clarity",
    "Email : EMAIL Q2.5 — Rate the explanation of boundary pair \"EMAIL 5\" : Correct": "email_5_correctness",
    "Email : EMAIL Q2.5 — Rate the explanation of boundary pair \"EMAIL 5\" : Complete": "email_5_completeness",
    "Email : EMAIL Q2.5 — Rate the explanation of boundary pair \"EMAIL 5\" : Useful": "email_5_usefulness",
    "Email : EMAIL Q2.6 What would improve Clarity for you?": "text_email_clarity",
    "Email : EMAIL Q2.7 What would improve Correctness for you?": "text_email_correctness",
    "Email : EMAIL Q2.8 What would improve Completeness for you?": "text_email_completeness",
    "Email : EMAIL Q2.9 What would improve Usefulness for you?": "text_email_usefulness",
    "Bytecount : BC Q3.1 — Rate the explanation of boundary pair \"BC 1\" : Clear": "bytecnt_1_clarity",
    "Bytecount : BC Q3.1 — Rate the explanation of boundary pair \"BC 1\" : Correct": "bytecnt_1_correctness",
    "Bytecount : BC Q3.1 — Rate the explanation of boundary pair \"BC 1\" : Complete": "bytecnt_1_completeness",
    "Bytecount : BC Q3.1 — Rate the explanation of boundary pair \"BC 1\" : Useful": "bytecnt_1_usefulness",
    "Bytecount : BC Q3.2 — Rate the explanation of boundary pair \"BC 2\" : Clear": "bytecnt_2_clarity",
    "Bytecount : BC Q3.2 — Rate the explanation of boundary pair \"BC 2\" : Correct": "bytecnt_2_correctness",
    "Bytecount : BC Q3.2 — Rate the explanation of boundary pair \"BC 2\" : Complete": "bytecnt_2_completeness",
    "Bytecount : BC Q3.2 — Rate the explanation of boundary pair \"BC 2\" : Useful": "bytecnt_2_usefulness",
    "Bytecount : BC Q3.3 — Rate the explanation of boundary pair \"BC 3\" : Clear": "bytecnt_3_clarity",
    "Bytecount : BC Q3.3 — Rate the explanation of boundary pair \"BC 3\" : Correct": "bytecnt_3_correctness",
    "Bytecount : BC Q3.3 — Rate the explanation of boundary pair \"BC 3\" : Complete": "bytecnt_3_completeness",
    "Bytecount : BC Q3.3 — Rate the explanation of boundary pair \"BC 3\" : Useful": "bytecnt_3_usefulness",
    "Bytecount : BC Q3.4 — Rate the explanation of boundary pair \"BC 4\" : Clear": "bytecnt_4_clarity",
    "Bytecount : BC Q3.4 — Rate the explanation of boundary pair \"BC 4\" : Correct": "bytecnt_4_correctness",
    "Bytecount : BC Q3.4 — Rate the explanation of boundary pair \"BC 4\" : Complete": "bytecnt_4_completeness",
    "Bytecount : BC Q3.4 — Rate the explanation of boundary pair \"BC 4\" : Useful": "bytecnt_4_usefulness",
    "Bytecount : BC Q3.5 — Rate the explanation of boundary pair \"BC 5\" : Clear": "bytecnt_5_clarity",
    "Bytecount : BC Q3.5 — Rate the explanation of boundary pair \"BC 5\" : Correct": "bytecnt_5_correctness",
    "Bytecount : BC Q3.5 — Rate the explanation of boundary pair \"BC 5\" : Complete": "bytecnt_5_completeness",
    "Bytecount : BC Q3.5 — Rate the explanation of boundary pair \"BC 5\" : Useful": "bytecnt_5_usefulness",
    "Bytecount : BC Q3.6 What would improve Clarity for you?": "text_bytecnt_clarity",
    "Bytecount : BC Q3.7 What would improve Correctness for you?": "text_bytecnt_correctness",
    "Bytecount : BC Q3.8 What would improve Completeness for you?": "text_bytecnt_completeness",
    "Bytecount : BC Q3.9 What would improve Usefulness for you?": "text_bytecnt_usefulness",
    "Date : Date Q4.1 — Rate the explanation of boundary pair \"Date 1\" : Clear": "date_1_clarity",
    "Date : Date Q4.1 — Rate the explanation of boundary pair \"Date 1\" : Correct": "date_1_correctness",
    "Date : Date Q4.1 — Rate the explanation of boundary pair \"Date 1\" : Complete": "date_1_completeness",
    "Date : Date Q4.1 — Rate the explanation of boundary pair \"Date 1\" : Useful": "date_1_usefulness",
    "Date : Date Q4.2 — Rate the explanation of boundary pair \"Date 2\" : Clear": "date_2_clarity",
    "Date : Date Q4.2 — Rate the explanation of boundary pair \"Date 2\" : Correct": "date_2_correctness",
    "Date : Date Q4.2 — Rate the explanation of boundary pair \"Date 2\" : Complete": "date_2_completeness",
    "Date : Date Q4.2 — Rate the explanation of boundary pair \"Date 2\" : Useful": "date_2_usefulness",
    "Date : Date Q4.3 — Rate the explanation of boundary pair \"Date 3\" : Clear": "date_3_clarity",
    "Date : Date Q4.3 — Rate the explanation of boundary pair \"Date 3\" : Correct": "date_3_correctness",
    "Date : Date Q4.3 — Rate the explanation of boundary pair \"Date 3\" : Complete": "date_3_completeness",
    "Date : Date Q4.3 — Rate the explanation of boundary pair \"Date 3\" : Useful": "date_3_usefulness",
    "Date : Date Q4.4 — Rate the explanation of boundary pair \"Date 4\" : Clear": "date_4_clarity",
    "Date : Date Q4.4 — Rate the explanation of boundary pair \"Date 4\" : Correct": "date_4_correctness",
    "Date : Date Q4.4 — Rate the explanation of boundary pair \"Date 4\" : Complete": "date_4_completeness",
    "Date : Date Q4.4 — Rate the explanation of boundary pair \"Date 4\" : Useful": "date_4_usefulness",
    "Date : Date Q4.5 — Rate the explanation of boundary pair \"Date 5\" : Clear": "date_5_clarity",
    "Date : Date Q4.5 — Rate the explanation of boundary pair \"Date 5\" : Correct": "date_5_correctness",
    "Date : Date Q4.5 — Rate the explanation of boundary pair \"Date 5\" : Complete": "date_5_completeness",
    "Date : Date Q4.5 — Rate the explanation of boundary pair \"Date 5\" : Useful": "date_5_usefulness",
    "Date : Date Q4.6 What would improve Clarity for you?": "text_date_clarity",
    "Date : Date Q4.7 What would improve Correctness for you?": "text_date_correctness",
    "Date : Date Q4.8 What would improve Completeness for you?": "text_date_completeness",
    "Date : Date Q4.9 What would improve Usefulness for you?": "text_date_usefulness",
    "BMI : BMI Q5.1 — Rate the explanation of boundary pair \"BMI 1\" : Clear": "bmi_1_clarity",
    "BMI : BMI Q5.1 — Rate the explanation of boundary pair \"BMI 1\" : Correct": "bmi_1_correctness",
    "BMI : BMI Q5.1 — Rate the explanation of boundary pair \"BMI 1\" : Complete": "bmi_1_completeness",
    "BMI : BMI Q5.1 — Rate the explanation of boundary pair \"BMI 1\" : Useful": "bmi_1_usefulness",
    "BMI : BMI Q5.2 — Rate the explanation of boundary pair \"BMI 2\" : Clear": "bmi_2_clarity",
    "BMI : BMI Q5.2 — Rate the explanation of boundary pair \"BMI 2\" : Correct": "bmi_2_correctness",
    "BMI : BMI Q5.2 — Rate the explanation of boundary pair \"BMI 2\" : Complete": "bmi_2_completeness",
    "BMI : BMI Q5.2 — Rate the explanation of boundary pair \"BMI 2\" : Useful": "bmi_2_usefulness",
    "BMI : BMI Q5.3 — Rate the explanation of boundary pair \"BMI 3\" : Clear": "bmi_3_clarity",
    "BMI : BMI Q5.3 — Rate the explanation of boundary pair \"BMI 3\" : Correct": "bmi_3_correctness",
    "BMI : BMI Q5.3 — Rate the explanation of boundary pair \"BMI 3\" : Complete": "bmi_3_completeness",
    "BMI : BMI Q5.3 — Rate the explanation of boundary pair \"BMI 3\" : Useful": "bmi_3_usefulness",
    "BMI : BMI Q5.4 — Rate the explanation of boundary pair \"BMI 4\" : Clear": "bmi_4_clarity",
    "BMI : BMI Q5.4 — Rate the explanation of boundary pair \"BMI 4\" : Correct": "bmi_4_correctness",
    "BMI : BMI Q5.4 — Rate the explanation of boundary pair \"BMI 4\" : Complete": "bmi_4_completeness",
    "BMI : BMI Q5.4 — Rate the explanation of boundary pair \"BMI 4\" : Useful": "bmi_4_usefulness",
    "BMI : BMI Q5.5 — Rate the explanation of boundary pair \"BMI 5\" : Clear": "bmi_5_clarity",
    "BMI : BMI Q5.5 — Rate the explanation of boundary pair \"BMI 5\" : Correct": "bmi_5_correctness",
    "BMI : BMI Q5.5 — Rate the explanation of boundary pair \"BMI 5\" : Complete": "bmi_5_completeness",
    "BMI : BMI Q5.5 — Rate the explanation of boundary pair \"BMI 5\" : Useful": "bmi_5_usefulness",
    "BMI : BMI Q5.6 What would improve Clarity for you?": "text_bmi_clarity",
    "BMI : BMI Q5.7 What would improve Correctness for you?": "text_bmi_correctness",
    "BMI : BMI Q5.8 What would improve Completeness for you?": "text_bmi_completeness",
    "BMI : BMI Q5.9 What would improve Usefulness for you?": "text_bmi_usefulness",
    "Thank you! : Q6.1 Would you use automated test generation tools that provide such explanations?": "use",
    "Thank you! : Q 6.2 Because...": "text_use_reason",
    "Thank you! : Q6.3 What one change would make these explanations more helpful for you?": "text_one_change",
    "Thank you! : Q6.4 – May we contact you for a short follow-up interview?": "contact",
    "Thank you! : yes, my email is:": "email",
    "Thank you! : Q6.5 – Any other comments or feedback?": "text_feedback"

}
